name: auto
on: push
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - run: 
            echo "hello anji"
            echo "this is github actions"
            echo "this is trigger"
            
     
